import type { LocaleCopy } from './model';

// Portfolio-authored presentation only. No duplicate technical metadata or documents.
export const finnish: LocaleCopy = {
  site: {
    role: 'Ohjelmisto- ja tekoälykehittäjä',
    location: 'Ulvila, Suomi',
    title: 'Ville Lähteenmäki — Ohjelmisto- ja tekoälykehittäjä',
    description: 'Ohjelmistoja, tietoon pohjautuvaa tekoälyä ja reaaliaikaisia järjestelmiä. Ville Lähteenmäen valitut kehitystyöt: ReorderOps, A Chain of Pain, StoryCodex ja Author Website.',
    hero: {
      label: 'Oma portfolio / Valitut työt',
      lines: ['Ohjelmistoja.', 'Tekoälyä.', 'Tehty harkiten.'],
      summary: 'Rakennan luotettavia ohjelmistoja, tekoälyavusteisia työnkulkuja ja käytännön automaatiota. Hankintapäätöksistä reaaliaikaisiin pelijärjestelmiin.',
    },
    navigationLabels: { work: 'Projektit', approach: 'Työtapa', background: 'Tausta', contact: 'Yhteystiedot' },
    cvLabel: 'CV · PDF', cvDownloadLabel: 'Lataa CV',
    selection: 'Valikoima viimeaikaisia ja teknisesti olennaisia töitä.',
    workflow: {
      title: 'Nopeuta työtä.\nVarmista tulos.',
      summary: 'Tekoäly tukee toteutusta, analyysiä ja iterointia. Oikeellisuus varmistetaan testeillä, tarkastuksilla ja validoinnilla. ReorderOps tekee tämän eron näkyväksi sekä kehitystyössä että itse tuotteessa.',
      steps: [
        { title: 'Määrittele rajat', description: 'Jaa ongelma tietosopimuksiin, deterministisiin sääntöihin ja selkeästi rajattuihin toimintoihin.' },
        { title: 'Toteuta pienissä osissa', description: 'Käytä koodausagentteja rajatun kontekstin kanssa toteutuksessa, virheenjäljityksessä ja katselmoinnissa. Pidä muutokset tarkasteltavina Gitissä.' },
        { title: 'Haasta tulos', description: 'Testaa virhetilanteita, vanhentunutta tilaa, virheellisiä syötteitä ja hyökkääviä kehotteita. Vertaa tekoälyn selityksiä taustajärjestelmän tietoihin.' },
        { title: 'Varmista ennen toimintoa', description: 'Tarkasta toiminta ja sen perustelut. Säilytä tiedossa olevat rajoitteet ja käytä determinististä varatoimintoa, kun tekoälyyn ei voi luottaa.' },
      ],
    },
    skillLabels: { core: 'Ohjelmointikielet', development: 'Sovelluskehitys', ai: 'Tekoäly ja kehitystyö', infrastructure: 'Data ja infrastruktuuri' },
    skillTerms: { llmApis: 'LLM-rajapinnat', codingAgents: 'Koodausagentit', aiEvaluation: 'Tekoälyn arviointi', promptContext: 'Kehotteiden ja kontekstin suunnittelu', aiDebugReview: 'Tekoälyavusteinen virheenjäljitys ja katselmointi', restApis: 'REST-rajapinnat' },
    earlier: 'Muuta kokemusta on kertynyt Kotlinista ja Jetpack Composesta, C#:sta ja .NET MAUIsta, UiPath StudioX:stä, Power BI:stä ja Power Pivotista sekä Power Appsista ja Power Automatesta mobiilisovellusten, automaation ja opintoprojektien kautta.',
    background: {
      title: 'Käytännön järjestelmiä.\nLaajempi näkökulma.',
      summary: 'Työni ulottuu liiketoimintasovelluksista mobiiliohjelmistoihin ja vuorovaikutteisiin ympäristöihin. Yhteistä niille on monimutkaisen toiminnan tekeminen ymmärrettäväksi, tarkasteltavaksi ja hyödylliseksi.',
      education: { institution: 'Savonia-ammattikorkeakoulu', qualification: 'IT-tradenomiopinnot (Business Information Technology)', note: 'Ohjelmistokehitystä, tiedonhallintaa, analytiikkaa, automaatiota ja projektityötä. Valmistumista ei ole vahvistettu.' },
    },
    contact: { title: 'Rakennetaan\njotain hyödyllistä.', description: 'Ota yhteyttä ohjelmistoihin, tekoälyn työnkulkuihin tai tekniseen tuotekehitykseen liittyen.' },
  },
  evidencePath: ['Data', 'Deterministinen logiikka', 'Jäsennellyt perustelut', 'Tekoälyn tulkinta', 'Ihmisen hyväksyntä', 'Validoitu toiminto', 'Tapahtumaloki'],
  projects: {
    reorderops: {
      category: 'Varastonhallinta ja hankintasuunnittelu',
      description: 'Varastotiedoista hankintapäätökseen, jonka perusteet voi tarkastaa.',
      summary: 'Deterministinen hankintasuunnittelu, muuttumattomat perustelut ja tuloksia selittävä tekoälyavustaja. Ihminen tarkastaa päätöksen, ja taustajärjestelmä validoi sen uudelleen ennen sisäisen tilausluonnoksen luomista.',
      role: 'Sovelluksen suunnittelu ja toteutus', status: 'Julkinen portfoliodemo',
      highlights: ['Toistettavat suunnittelusäännöt', 'Uudelleen validoitu ihmisen hyväksyntä', 'Tietoon pohjautuva tekoäly, vain luku'],
      architecture: 'React- ja TypeScript-käyttöliittymä → FastAPI-liiketoimintasäännöt → SQLiteen tallennetut perustelut ja toiminnan tila. Rajattu tekoälysovitin lukee erillistä tietopakettia; hyväksytyt toiminnot validoivat nykytilan uudelleen transaktion sisällä.',
      challenges: ['Erota historialliset havainnot synteettisistä toiminnan syötteistä.', 'Säilytä tallennetut perustelut muuttumattomina ja estä vanhentuneen tiedon hyväksyntä.', 'Käsittele tekoälyn kelvollisia viitteitä ja selitystekstin oikeellisuutta erillisinä varmennusongelmina.'],
      verification: ['Automaattiset tarkistukset kattavat virheelliset syötteet, tulosten toistamisen, rinnakkaisuuden, peruutukset, vanhentuneen tiedon hyväksynnät ja vierailijoiden eristämisen.', 'Monikieliset, epäsiistejä syötteitä käsittelevät ja hyökkäävät tekoälyarvioinnit säilyttävät havaitut merkitys- ja kielivirheet.', 'Dokumentoitu planning-v1.4-vaihe raportoi 303 läpäistyä taustajärjestelmän testiä Pythonin versioilla 3.11 ja 3.12 sekä Ruff-, TypeScript- ja tuotantokoontitarkistukset. Tämä on projektin lähdeaineistoa, ei tämän portfolion testimäärä.'],
      placeholders: ['Julkinen lähdekoodilinkki: repositorion osoite palautti tarkistuksessa HTTP 404 -vastauksen ilman kirjautumista.', 'Selostettu esittelyvideo voidaan lisätä.'],
      linkLabels: { demo: 'Avaa demo', github: 'Lähdekoodi', caseStudy: 'Lue projektiesittely' },
      mediaText: { alt: 'ReorderOpsin julkinen varastonäkymä: historiallinen suunnittelupäivä, ilmoitus synteettisestä datasta, varastomittarit ja tuotetaulukko.', caption: 'Julkinen demo / Varaston tarkastelu. Kuvattu 3.10.2026. Kaikki näkyvät toiminnan tiedot ovat synteettisiä.' },
      study: [
        { title: 'Ongelma', paragraphs: ['Varastosuunnittelijan täytyy ymmärtää, mitkä tuotteet vaativat huomiota, miksi ja minkä toimenpiteen voi turvallisesti ottaa tarkasteluun. Pieni varasto ei yksin ole tilausohje: saapuvat toimitukset, toimitusajat, kysynnän muutokset ja toimittajan ehdot vaikuttavat päätökseen.', 'Ensimmäinen historiallisten tietojen tarkastelu käytti kiinteitä riittävyysluokkia. Ne tuottivat lähdeaineistossa paljon kohinaa. Tuotekohtaiset prosenttipisteet paransivat vertailua, mutta historiallisesti tavallinen varastotaso ei välttämättä kata toimittajan toimitusaikaa. Hankintasuunnittelusta tehtiin siksi erillinen deterministinen laskenta.'] },
        { title: 'Toistettava suunnittelu', paragraphs: ['Liiketoimintasäännöt ennustavat varastotilannetta ja laskevat täydennystarpeen toimitusaikojen, varmuusvaraston, vähimmäistilausten ja pakkauskokojen perusteella. Tallennetut ajot säilyttävät syötteet, laskentaversion ja syötteiden sormenjäljen sen sijaan, että vanhoja perusteluja laskettaisiin huomaamatta uudelleen.'], bullets: ['FILTER-420: suositus on 210 yksikköä, ja aiempaan puutteeseen liittyy kiirehtimisen tarkastelu.', 'VALVE-88: alkuperäinen 75 yksikön tarve kasvaa 120 yksikköön toimittajan vähimmäistilauksen vuoksi.', 'BELT-210: ajoissa saapuva toimitus estää päällekkäisen tilauksen.', 'BEARING-51: kysyntäpoikkeama pysäyttää suosituksen tarkasteltavaksi.'] },
        { title: 'Ihmisen päätös, uusi validointi', paragraphs: ['Hyväksyntä lukee nykyisen varaston, saapuvat toimitukset, kysynnän ja toimittajaehdot uudelleen lyhyen SQLite-kirjoitustransaktion sisällä. Muuttuneet perustelut estävät toiminnon. Täsmälleen saman pyynnön uusiminen palauttaa alkuperäisen tuloksen, ja yksilöllisyysrajoitteet estävät toisen aktiivisen luonnoksen samalle tuotteelle.', 'Sisäiset ostotilausluonnokset eivät lähetä mitään toimittajalle eivätkä muutu vahvistetuksi saapuvaksi toimitukseksi. Onnistuneet ja estetyt toiminnot tallentuvat vain täydentyvään tapahtumalokiin. Tietokantatiedoston tai skeeman suora muokkausoikeus mahdollistaa silti tietojen muuttamisen; tallennusta ei väitetä peukaloinnin estäväksi.'] },
        { title: 'Rajattu tekoälytulkinta', paragraphs: ['GPT-6 Luna -integraatio käyttää hallittuja, vain lukuun tarkoitettuja työkaluja erillisen tietopaketin hakemiseen ja varmennettujen tietokorttien yhdistämiseen sovellukseen. Määräävät lukumäärät kuuluvat taustajärjestelmälle. Avustaja ei voi hyväksyä päätöksiä, luoda luonnoksia, muokata varastoa tai lähettää tilauksia.', 'Arvioinnit sisältävät monikielisiä kysymyksiä, epäsiistejä syötteitä ja kehoteinjektioyrityksiä. Ne paljastivat tärkeän rajoitteen: oikeat lähdeviitteet eivät takaa järkevää selitystä tai pyydettyä kieltä. Deterministinen varatoiminto säilyttää hyödylliset tiedot, kun palveluntarjoaja epäonnistuu tai käyttöraja täyttyy. Tekoälyn selitykset vaativat edelleen tarkastamista.'] },
        { title: 'Julkinen demo, eristetyt toiminnot', paragraphs: ['Vercelin käyttöliittymä ja Railwayn taustajärjestelmä esittävät generoitua historiaa yksityisen CSV-aineiston sijaan, sillä sen alkuperää ja lisenssiä ei ole vahvistettu. Vierailijat saavat erilliset väliaikaiset tietokantakopiot, jolloin luonnokset ja lokitapahtumat pysyvät erillään.', 'Pysyvä käytönhallintarekisteri varaa arvioidut tekoälykustannukset ennen palvelukutsua ja soveltaa käyttörajoja. Epävarmassa tilanteessa varaus säilytetään. Kyse on kustannusten hallinnasta, ei väitteestä mitatuista käyttösäästöistä.'] },
        { title: 'Varmennus ja avoimet rajoitteet', paragraphs: ['Testit kattavat puuttuvat ja virheelliset tiedot, laskennan raja-arvot, tallennettujen ajojen toistamisen, vanhentuneet hyväksynnät, transaktioiden peruutukset, rinnakkaisuuden, vierailijoiden eristämisen ja palautuksen. Dokumentoitu v1.4-vaihe raportoi 303 läpäistyä taustajärjestelmän testiä Pythonin versioilla 3.11 ja 3.12 sekä Ruff- ja käyttöliittymätarkistukset.', 'Dokumentoidut julkaistun demon tarkistukset kattavat hankintatoiminnot ja rajatun tekoälykäytön. Kielen luotettavuus, palveluntarjoajan käytön täsmäytys, täysi tuotantopalautus ja kylmäkäynnistyksen ajoitus vaativat vielä varmennusta. Projektissa ei ole reaaliaikaista ERP-integraatiota, tilausten lähettämistä toimittajalle, vastaanottotyönkulkua, poikkeaman ohitusta tai varsinaista käyttäjätunnistautumista. Se osoittaa teknisiä ratkaisuja, ei mitattua ennustetarkkuutta tai vähittäiskaupan säästöjä.'] },
      ],
    },
    'a-chain-of-pain': {
      category: 'Ensimmäisen persoonan tarinapeli',
      description: 'Toisenlainen järjestelmä. Maailma ensimmäisen persoonan näkökulmasta.',
      summary: 'Unreal Engine 5:llä ja C++:lla rakennettu ensimmäisen persoonan tarinapeli. Reaaliaikainen vastapari tämän valikoiman liiketoimintasovelluksille.',
      role: null, status: 'Projektin dokumentaatio tulossa',
      highlights: ['Ensimmäisen persoonan tarina', 'Reaaliaikainen kehitys', 'Unreal Engine 5 / C++'],
      architecture: 'Unreal Engine 5 / C++. Tarkempi pelijärjestelmien arkkitehtuuri odottaa projektinäyttöä.',
      challenges: [], verification: [],
      placeholders: ['Pelikuvakaappaukset ja video', 'Kehitysrooli ja nykyisen version tilanne', 'Varmennettu pelijärjestelmien rakenne', 'Näyttö vihollisen havainnoinnista, tutkimisesta, takaa-ajosta ja etsimisestä, jos nämä on toteutettu', 'Testausmuistiinpanot ja julkiset lähdekoodi- tai latauslinkit'],
      linkLabels: { demo: 'Avaa demo', github: 'Lähdekoodi', caseStudy: 'Projektin tiedot' }, mediaText: null,
      study: [
        { title: 'Vahvistettu projektin laajuus', paragraphs: ['A Chain of Pain on Unreal Engine 5:llä ja C++:lla rakennettu ensimmäisen persoonan tarinapeli. Se tuo reaaliaikaisen ja C++-kehityksen osaksi portfoliota, jonka muut työt painottuvat sovelluksiin ja tekoälyavusteisiin työnkulkuihin.'] },
        { title: 'Täydennettävä näyttö', paragraphs: ['Pelikuva-aineistoa ja teknistä dokumentaatiota ei ole vielä toimitettu. Niille on jätetty tällä sivulla selkeä paikka. Vihollisten tarkkaa toimintaa, haarautuvia lopputuloksia, uudelleenkäytettäviä järjestelmiä ja kehitysvastuuta kuvataan vasta, kun projektiaineisto tukee väitteitä.'] },
      ],
    },
    storycodex: {
      category: 'Android / Tekoälytarinat', description: 'Pieni käyttöliittymä suurelle mielikuvitukselle.',
      summary: 'Android-tarinasovellus, jossa lapset valitsevat hahmot, paikan ja juonen. Kielimalli luo suomenkielisen tarinan, Androidin puhesynteesi lukee sen ääneen ja välimuistiin tallennetut tarinat ovat käytettävissä ilman verkkoyhteyttä.',
      role: null, status: 'Portfolioprojekti',
      highlights: ['Tarinoiden luonti painikkeilla', 'Suomenkielinen luonti ja kerronta', 'Tallennettujen tarinoiden käyttö ilman verkkoa'],
      architecture: 'Jetpack Compose -Android-sovellus, taustarajapinta ja kielimalli-integraatio sekä Androidin puhesynteesi ja tarinoiden välimuisti.',
      challenges: ['Lapsille suunnattu turvallisuuspainotteinen käyttöliittymä ja hallitut kehotteet.'], verification: [],
      placeholders: ['Varmennetut kuvakaappaukset', 'Julkinen lähdekoodi- tai julkaisulinkki', 'Muodollinen arviointi- ja testausnäyttö'],
      linkLabels: { demo: 'Avaa demo', github: 'Lähdekoodi', caseStudy: 'Projektin esittely' }, mediaText: null,
      study: [
        { title: 'Helposti lähestyttävä tarinanluonti', paragraphs: ['Lapset valitsevat hahmot, paikan ja juonen painikkeilla. Sovellus lähettää hallitun kehotteen taustarajapintansa kautta ja tuottaa lapsille suunnatun suomenkielisen tarinan. Androidin puhesynteesi lukee tarinan ääneen.'] },
        { title: 'Hyödyllinen ilman verkkoyhteyttä', paragraphs: ['Verkoton käyttö perustuu aiemmin välimuistiin tallennettuihin tarinoihin. Se ei tarkoita paikallista kielimallin käyttöä. Alkuperäinen portfolio kertoo Kotlinista, Jetpack Composesta, Androidin puhesynteesistä, OpenAI-kielimallirajapinnasta ja taustarajapinnasta.'] },
        { title: 'Suunnittelun lähtökohdat', paragraphs: ['Nykyinen projektikuvaus korostaa turvallisuuspainotteista sovellussuunnittelua ja hallittuja kehotteita. Muodollisen lapsiturvallisuusarvioinnin tuloksia tai julkaisulinkkejä ei ole toimitettu, joten turvallisuuden varmennusta ei väitetä tehdyksi.'] },
      ],
    },
    'author-website': {
      category: 'Full-stack / Palvelimeton verkkosovellus', description: 'Kirjailijasivusto ja sen ylläpidon työkalut.',
      summary: 'Kaksikielinen kirjailijasivusto, jossa on kirjojen hallinta, JWT-pohjainen ylläpitäjän kirjautuminen ja yhteydenottorajapinta. Staattiset sivut yhdistyvät Node.js-taustajärjestelmään, ja paikallinen kehitys käyttää Express-palvelinta.',
      role: null, status: 'Nykyinen verkkosivusto',
      highlights: ['Kaksikielinen staattinen käyttöliittymä', 'Kirjojen hallinta kirjautumisen takana', 'Paikallinen Express ja palvelimettomat rajapinnat'],
      architecture: 'HTML-, CSS- ja JavaScript-käyttöliittymä, palvelimettomat Node.js-rajapinnat, JWT-pohjainen ylläpitäjän kirjautuminen ja JSON-kirjatallennus. Express toteuttaa samat rajapinnat paikallisesti.',
      challenges: ['Pidä paikallinen kehitys ja palvelimeton toiminta yhdenmukaisina.', 'Erota julkiset kirjatiedot kirjautumista edellyttävästä hallinnasta.'], verification: [],
      placeholders: ['Sovelluksen oma kuvakaappaus'],
      linkLabels: { demo: 'Katso sivusto', github: 'Lähdekoodi', caseStudy: 'Projektin esittely' }, mediaText: null,
      study: [
        { title: 'Julkinen sivusto ja ylläpidon työnkulku', paragraphs: ['Kirjailijasivusto tarjoaa staattisia kaksikielisiä sivuja ja kirjatietoja. Ylläpitäjän käyttöliittymä tunnistautuu JWT:llä ja tukee kirjojen luontia, lukemista, muokkausta ja poistamista Node.js-rajapintojen kautta. Yhteydenottorajapinta välittää viestit määritetyn sähköpostipalvelun kautta.'] },
        { title: 'Kaksi ympäristöä, yksi työnkulku', paragraphs: ['Vercelin palvelimettomat rajapinnat palvelevat julkista sivustoa. Express-kehityspalvelin toteuttaa kirjojen ja yhteydenottojen rajapinnat paikallisesti. Kirjatiedot tallennetaan JSON-tiedostoon; projektin dokumentaatio tunnistaa varsinaisen tietokannan tulevaksi vaihtoehdoksi rinnakkaisiin tuotantokirjoituksiin.'] },
        { title: 'Säilytetty portfolion rinnalla', paragraphs: ['Portfolion uudistus säilyttää kirjailijasivut, rajapintakäsittelijät, kirjatiedot ja ylläpitäjän käyttöliittymän. TypeScript-pohjainen sisällöntuotanto luo staattisen portfolion ilman uutta sovelluskehystä tai muutoksia julkaisupalvelun asetuksiin.'] },
      ],
    },
  },
};
