import type { Locale } from './model';

// Portfolio UI only. Technical filenames, product names and documentation stay shared.
const messages = {
  skip: { en: 'Skip to content', fi: 'Siirry sisältöön' },
  home: { en: 'portfolio home', fi: 'portfolion etusivu' },
  mainNavigation: { en: 'Main navigation', fi: 'Päänavigaatio' },
  languageNavigation: { en: 'Language', fi: 'Kieli' },
  newTab: { en: 'opens in a new tab', fi: 'avautuu uuteen välilehteen' },
  technologies: { en: 'technologies', fi: 'teknologiat' },
  motion: { en: 'Motion', fi: 'Liike' },
  motionOn: { en: 'on', fi: 'päällä' },
  motionOff: { en: 'off', fi: 'pois' },
  motionEnable: { en: 'Enable spatial motion', fi: 'Ota tilallinen liike käyttöön' },
  motionDisable: { en: 'Disable spatial motion', fi: 'Poista tilallinen liike käytöstä' },
  footer: { en: 'Software. Evidence. Human judgment.', fi: 'Ohjelmistoja. Näyttöä. Ihmisen harkintaa.' },
  backTop: { en: 'Back to top', fi: 'Takaisin alkuun' },
  architecture: { en: 'Architecture', fi: 'Arkkitehtuuri' },
  operationalData: { en: 'Operational data', fi: 'Toiminnan tiedot' },
  dataInputs: { en: 'Stock · demand · supplier policy', fi: 'Varasto · kysyntä · toimittajaehdot' },
  authoritativeCalculation: { en: 'Authoritative calculation', fi: 'Päätöksen perustana' },
  planningEngine: { en: 'Deterministic\nplanning engine', fi: 'Deterministinen\nsuunnittelu' },
  savedEvidence: { en: 'Saved, immutable evidence', fi: 'Tallennetut, muuttumattomat perustelut' },
  interpret: { en: 'Interpret', fi: 'Tulkinta' },
  readOnlyAI: { en: 'Read-only AI', fi: 'Tekoäly, vain luku' },
  explainEvidence: { en: 'Explain the evidence', fi: 'Selittää perustelut' },
  review: { en: 'Review', fi: 'Tarkistus' },
  humanApproval: { en: 'Human approval', fi: 'Ihmisen hyväksyntä' },
  revalidate: { en: 'Revalidate before action', fi: 'Uusi tarkistus ennen toimintoa' },
  internalDraft: { en: 'Internal draft', fi: 'Sisäinen tilausluonnos' },
  audit: { en: 'Audit trail', fi: 'Tapahtumaloki' },
  architectureCaption: { en: 'System architecture · AI interprets. Business rules decide.', fi: 'Järjestelmän rakenne · Tekoäly tulkitsee. Liiketoimintasäännöt ratkaisevat.' },
  project: { en: 'Project', fi: 'Projekti' },
  flagship: { en: 'Flagship project', fi: 'Pääprojekti' },
  featured: { en: 'Featured project', fi: 'Esittelyssä' },
  decisionPath: { en: 'The decision path', fi: 'Päätöksen kulku' },
  exploreProjects: { en: 'Explore projects', fi: 'Tutustu projekteihin' },
  contact: { en: 'Contact', fi: 'Ota yhteyttä' },
  scrollExplore: { en: 'Scroll to explore', fi: 'Jatka vierittämällä' },
  selectedProjects: { en: 'Selected projects', fi: 'Valitut projektit' },
  selectedWork: { en: 'Selected work', fi: 'Muita valittuja töitä' },
  moreWays: { en: 'More ways to build.', fi: 'Muita tapoja rakentaa.' },
  mobileWeb: { en: 'Mobile experiences and the web.', fi: 'Mobiilisovelluksia ja verkkopalveluita.' },
  workflow: { en: 'Development / AI workflow', fi: 'Kehitystyö / Tekoäly' },
  reorderEvidence: { en: 'See the ReorderOps evidence', fi: 'Tutustu ReorderOpsin näyttöön' },
  skills: { en: 'Skills / Technologies', fi: 'Osaaminen / Teknologiat' },
  toolsBehind: { en: 'Tools behind the work.', fi: 'Työn taustalla olevat työkalut.' },
  toolsGrouping: { en: 'Grouped by where they earn their place.', fi: 'Ryhmitelty käyttötarkoituksen mukaan.' },
  earlierWork: { en: 'Earlier work & additional experience', fi: 'Aiemmat työt ja muu kokemus' },
  background: { en: 'Background / Education', fi: 'Tausta / Koulutus' },
  education: { en: 'Education', fi: 'Koulutus' },
  educationDetails: { en: 'Software development, data management, analytics, automation and project work.', fi: 'Ohjelmistokehitystä, tiedonhallintaa, analytiikkaa, automaatiota ja projektityötä.' },
  contactSection: { en: 'Contact', fi: 'Yhteys' },
  backWork: { en: 'Back to selected work', fi: 'Takaisin valittuihin töihin' },
  status: { en: 'Status', fi: 'Tilanne' },
  role: { en: 'Role', fi: 'Rooli' },
  fullScreenshot: { en: 'View full-size {project} screenshot', fi: 'Katso projektin {project} kuvakaappaus täysikokoisena' },
  imageHint: { en: 'Select the image to view full size.', fi: 'Avaa kuva täysikokoisena valitsemalla se.' },
  caseNavigation: { en: 'Case study sections', fi: 'Projektiesittelyn osiot' },
  inStudy: { en: 'In this study', fi: 'Tässä esittelyssä' },
  verification: { en: 'Verification record', fi: 'Testaus ja varmennus' },
  sources: { en: 'Source material', fi: 'Lähdeaineisto' },
  sourcesIntro: { en: 'This presentation is grounded in the following project material.', fi: 'Tämä esittely perustuu seuraavaan projektiaineistoon.' },
  browseDocs: { en: 'Browse project documentation', fi: 'Tutustu projektin dokumentaatioon' },
  documentationEnglish: { en: 'Documentation · English', fi: 'Dokumentaatio · englanniksi' },
  documentation: { en: 'Documentation', fi: 'Dokumentaatio · englanniksi' },
  documentationSummary: { en: 'For a deeper engineering review, read the curated reviewer guide, architecture, planning rules, AI evaluation and public-demo controls. These technical documents are available in English.', fi: 'Teknistä arviointia varten tarjolla ovat kuratoitu arvioijan opas, arkkitehtuuri, suunnittelusäännöt, tekoälyn arviointi ja julkisen demon hallintakeinot. Tekninen dokumentaatio on englanniksi.' },
  sourceLegacy: { en: 'Preserved original portfolio content', fi: 'Säilytetty alkuperäisen portfolion sisältö' },
  sourceRepository: { en: 'Existing repository README.md, api/, js/admin.js and dev-server.js', fi: 'Projektin nykyiset README.md, api/, js/admin.js ja dev-server.js' },
  sourceOriginal: { en: 'Original portfolio content', fi: 'Alkuperäisen portfolion sisältö' },
  sourceGame: { en: 'Project C++ systems, milestone history and recorded in-editor regression evidence (reviewed 3 October 2026); gameplay captures from the current playable build.', fi: 'Projektin C++-järjestelmät, kehitysvaiheiden historia ja tallennetut editorin regressiotestit (tarkastettu 3.10.2026) sekä pelikuvat nykyisestä pelattavasta versiosta.' },
  videoFallback: { en: 'Download gameplay video', fi: 'Lataa pelivideo' },
  videoSequence: { en: 'In the sequence', fi: 'Videon kulku' },
  fullImage: { en: 'View full-size image: {title}', fi: 'Katso kuva täysikokoisena: {title}' },
  exploreRest: { en: 'Explore the rest', fi: 'Tutustu muihin töihin' },
  returnProjects: { en: 'Return to selected projects', fi: 'Takaisin valittuihin projekteihin' },
  notFoundTitle: { en: 'Page not found', fi: 'Sivua ei löydy' },
  notFoundDescription: { en: 'This page could not be found. Return to the portfolio and selected projects.', fi: 'Sivua ei löytynyt. Palaa portfolioon ja tutustu valittuihin projekteihin.' },
  notFoundHeading: { en: 'This path ends here.', fi: 'Tämä polku päättyy tähän.' },
  notFoundText: { en: 'The page may have moved. Explore the selected projects or get in touch.', fi: 'Sivu on saattanut siirtyä. Tutustu valittuihin projekteihin tai ota yhteyttä.' },
  returnPortfolio: { en: 'Return to portfolio', fi: 'Takaisin portfolioon' },
  socialAlt: { en: 'Ville Lähteenmäki — Software & AI Developer. Selected work: ReorderOps, A Chain of Pain, StoryCodex and Author Website.', fi: 'Ville Lähteenmäki — Ohjelmisto- ja tekoälykehittäjä. Valitut työt: ReorderOps, A Chain of Pain, StoryCodex ja Author Website.' },
} as const;

export type UiText = Record<keyof typeof messages, string>;
export function getUi(locale: Locale): UiText {
  return Object.fromEntries(Object.entries(messages).map(([key, value]) => [key, value[locale]])) as UiText;
}
