// Generated from the StoryCodex app's selectable options (StoryViewModel.kt).
// The story endpoint accepts only these values, so no free text reaches the model.
// Regenerate if the app's option lists change.
const storyOptions = {
  "characters": {
    "FINNISH": [
      "Karhu",
      "Jänis",
      "Kettu",
      "Pöllö",
      "Kissa",
      "Koira",
      "Lohikäärme",
      "Robotti",
      "Orava",
      "Siili",
      "Pingviini",
      "Delfiini",
      "Norsu",
      "Susi",
      "Panda",
      "Peikko",
      "Yksisarvinen",
      "Hiiri",
      "Lammas",
      "Varis",
      "Kani",
      "Kotka",
      "Hanhi",
      "Ahma",
      "Saukko",
      "Merikotka",
      "Kameli",
      "Käärme",
      "Papukaija",
      "Kultakala",
      "Sammakko",
      "Rapu",
      "Seepra",
      "Kirahvi",
      "Leijona",
      "Tiikeri",
      "Muurahainen",
      "Mehiläinen",
      "Perhonen",
      "Pörriäishirviö",
      "Pilvihahmo",
      "Taikakani",
      "Metsänhenki",
      "Lumipupu",
      "Tulikorppi"
    ],
    "ENGLISH": [
      "Bear",
      "Rabbit",
      "Fox",
      "Owl",
      "Cat",
      "Dog",
      "Dragon",
      "Robot",
      "Squirrel",
      "Hedgehog",
      "Penguin",
      "Dolphin",
      "Elephant",
      "Wolf",
      "Panda",
      "Troll",
      "Unicorn",
      "Mouse",
      "Sheep",
      "Crow",
      "Bunny",
      "Eagle",
      "Goose",
      "Wolverine",
      "Otter",
      "Sea Eagle",
      "Camel",
      "Snake",
      "Parrot",
      "Goldfish",
      "Frog",
      "Crab",
      "Zebra",
      "Giraffe",
      "Lion",
      "Tiger",
      "Ant",
      "Bee",
      "Butterfly",
      "Buzzy Moose Monster",
      "Cloud Friend",
      "Magic Bunny",
      "Forest Spirit",
      "Snow Bunny",
      "Fire Raven"
    ]
  },
  "places": {
    "FINNISH": [
      "Metsä",
      "Niitty",
      "Järven ranta",
      "Vuori",
      "Pieni kylä",
      "Avaruus",
      "Satumetsä",
      "Sademetsä",
      "Meren pohja",
      "Kaupunki",
      "Puutarha",
      "Aavikko",
      "Lumimetsä",
      "Peltoniitty",
      "Kukkula",
      "Pilvilinna",
      "Taikapolku",
      "Vanha puutalo",
      "Kalatähtilaakso",
      "Satamaranta",
      "Vedenalainen luola",
      "Aurinkolaakso",
      "Kuutarhuri-keidas",
      "Tähtipuisto",
      "Metsäaukio",
      "Vuorenhuippu",
      "Veturiasema",
      "Leikkipuisto",
      "Kylätori",
      "Marjametsä"
    ],
    "ENGLISH": [
      "Forest",
      "Meadow",
      "Lakeside",
      "Mountain",
      "Small Village",
      "Space",
      "Fairy Forest",
      "Rainforest",
      "Sea Floor",
      "City",
      "Garden",
      "Desert",
      "Snowy Forest",
      "Field Meadow",
      "Hill",
      "Cloud Castle",
      "Magic Path",
      "Old Wooden House",
      "Starlake Valley",
      "Harbor Shore",
      "Underwater Cave",
      "Sunny Valley",
      "Moon Gardener Oasis",
      "Star Park",
      "Forest Clearing",
      "Mountain Peak",
      "Train Station",
      "Playground",
      "Village Square",
      "Berry Forest"
    ]
  },
  "plots": {
    "FINNISH": [
      "Etsitään kadonnut esine",
      "Opitaan jakamaan",
      "Selvitetään outo ääni",
      "Riita ratkeaa puhumalla",
      "Uusi ystävä löytyy",
      "Matka mystiseen paikkaan",
      "Rakennetaan jotain yhdessä",
      "Syntyy väärinkäsitys, joka ratkeaa",
      "Autetaan eksynyttä hahmoa",
      "Ystävykset keksivät uuden leikin",
      "Taikasiemen alkaa kasvaa",
      "Joku tarvitsee apua kantamisessa",
      "Etsitään piilotettu aarre",
      "Yritetään järjestää yllätys toiselle",
      "Juhlapäivä menee melkein sekaisin",
      "Päivän aikana opitaan uusi taito",
      "Kaverukset vaihtavat rooleja leikissä",
      "Luodaan salainen klubitalo",
      "Harjoitellaan rohkeutta pienissä asioissa",
      "Etsitään reitti kotiin rauhallisesti",
      "Ystävykset selvittävät hassun jäljen maassa",
      "Koottava palapeli katoaa",
      "Hahmot löytävät uuden paikan leikille",
      "Päivän pelastus tulee yhteistyöllä",
      "Järjestetään leikkikilpailu"
    ],
    "ENGLISH": [
      "A lost item is found",
      "Learning to share",
      "A mysterious sound is solved",
      "A misunderstanding is cleared up",
      "A new friend is found",
      "A journey to a mysterious place",
      "Building something together",
      "A mix-up that gets resolved",
      "Helping a lost character",
      "Friends invent a new game",
      "A magic seed starts to grow",
      "Someone needs help carrying",
      "Searching for a hidden treasure",
      "Planning a surprise for a friend",
      "A party day almost goes wrong",
      "Learning a new skill",
      "Friends switch roles in a game",
      "Creating a secret clubhouse",
      "Practicing courage in small things",
      "Finding the way home calmly",
      "Tracking a funny trail on the ground",
      "A jigsaw puzzle goes missing",
      "Finding a new place to play",
      "The day is saved by teamwork",
      "Hosting a friendly play contest"
    ]
  }
};

module.exports = { storyOptions };
